param(
  [string]$Root = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$excludeDirs = @("Projects", ".git", "node_modules", "bin", "obj", ".vs", ".idea")

$cachePath   = Join-Path $Root "tools/.skill-cache.json"
$outPath     = Join-Path $Root ".cursor/rules/90-active-skills.mdc"

function Get-WorkspaceSignature {
  # 快速簽章：只看少量關鍵檔案的 LastWriteTime，避免全量 hash
  $patterns = @("*.sln","*.csproj","Directory.Build.props","global.json","package.json","pnpm-lock.yaml","yarn.lock","pom.xml","build.gradle","settings.gradle")
  $items = @()

  foreach ($p in $patterns) {
    $found = Get-ChildItem -Path $Root -Recurse -File -Filter $p -ErrorAction SilentlyContinue |
      Where-Object {
        $parts = $_.FullName.Replace($Root,"").TrimStart("\","/").Split([IO.Path]::DirectorySeparatorChar)
        ($parts.Count -gt 0) -and ($excludeDirs -notcontains $parts[0])
      } |
      Select-Object -First 50  # 限制數量，signature 只需要代表性

    if ($found) { $items += $found }
  }

  # 加入 Workspace 設定檔
  $workspaceConfigs = @(
    (Join-Path $Root "agent/meta/version.md"),
    (Join-Path $Root "adapters/cursor/skill-detection.md")
  )

  foreach ($config in $workspaceConfigs) {
    if (Test-Path $config) {
      $items += Get-Item $config
    }
  }

  if (-not $items) {
    return @{ count = 0; maxWrite = "" }
  }

  $maxWrite = ($items | Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1).LastWriteTimeUtc.ToString("o")
  return @{ count = $items.Count; maxWrite = $maxWrite }
}

function Load-Cache {
  if (Test-Path $cachePath) {
    try { return Get-Content $cachePath -Raw | ConvertFrom-Json } catch { return $null }
  }
  return $null
}

function Save-Cache($obj) {
  $obj | ConvertTo-Json -Depth 10 | Set-Content -Path $cachePath -Encoding UTF8
}

function Find-Any($filters) {
  foreach ($f in $filters) {
    $hit = Get-ChildItem -Path $Root -Recurse -File -Filter $f -ErrorAction SilentlyContinue |
      Where-Object {
        $parts = $_.FullName.Replace($Root,"").TrimStart("\","/").Split([IO.Path]::DirectorySeparatorChar)
        ($parts.Count -gt 0) -and ($excludeDirs -notcontains $parts[0])
      } |
      Select-Object -First 1
    if ($hit) { return $true }
  }
  return $false
}

# ---- cache check ----
$signature = Get-WorkspaceSignature
$cache = Load-Cache

if ($cache -and $cache.signature.count -eq $signature.count -and $cache.signature.maxWrite -eq $signature.maxWrite) {
  Write-Host "No changes detected. Using cached skills."
  $skills = $cache.skills
} else {
  Write-Host "Changes detected. Scanning workspace for tech stack..."

  $enableShared   = $true
  $enableDotnet   = (Find-Any @("*.sln","*.csproj","Directory.Build.props","global.json"))
  $enableFrontend = (Find-Any @("package.json","pnpm-lock.yaml","yarn.lock"))
  $enableJava     = (Find-Any @("pom.xml","build.gradle","settings.gradle"))

  $skills = New-Object System.Collections.Generic.List[string]
  if ($enableShared)   { $skills.Add("skills/_shared") }
  if ($enableDotnet)   { $skills.Add("skills/dotnet") }
  if ($enableFrontend) { $skills.Add("skills/frontend") }
  if ($enableJava)     { $skills.Add("skills/java") }

  Save-Cache @{
    signature = $signature
    skills    = $skills
    updatedAt = (Get-Date).ToString("o")
  }
}

# ---- write 90-active-skills.mdc ----
$lines = @()
$lines += "alwaysApply: true"
$lines += ""
$lines += "# Active Skills (auto-generated)"
$lines += "Use the following skill packs as the first reference:"
foreach ($s in $skills) { $lines += "- /$s" }
$lines += ""
$lines += "Notes:"
$lines += "- Governance rules under /agent have higher priority than skills."
$lines += "- This file is generated by tools/update-cursor-skills.ps1."

$lines -join "`n" | Set-Content -Path $outPath -Encoding UTF8
Write-Host "Generated: $outPath"
Write-Host ("Enabled: " + ($skills -join ", "))
